[package]
name = "di"
version = "0.1.0"
authors = ["Sunli <scott_s829@163.com>"]
edition = "2018"

[dependencies]
di-derive = { version = "0.1.0", path = "di-derive" }
thiserror = "1.0"
anyhow = "1.0"
once_cell = "1.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
